In [37]:
import numpy as np
import numpy.linalg as linalg


S = np.matrix( [[ 97.18075394 , 4.01869602 , 77.40991318],      # B: ixN  BT: Nxi   : S = B*BT : i*i  : i = 3
                [ 4.01869602 ,108.87624652 , 8.93428697],
                [ 77.40991318 , 8.93428697 , 98.049557675]])
              
              
valsprops, vetsprops = np.linalg.eig(S)

ids_ord = valsprops.argsort()[::-1]


valsprops = (valsprops[ids_ord])

vetsprops = vetsprops[:, ids_ord]

traço = np.sum(valsprops)

valsprops, vetsprops, (valsprops[0] + valsprops[1])/traço


(array([176.27502282, 107.76237238,  20.06916293]),
 matrix([[ 0.69655167,  0.12282659, -0.70691542],
         [ 0.13494668, -0.99008273, -0.03905863],
         [ 0.70470219,  0.06818953,  0.70621882]]),
 0.9340061488417185)

In [38]:
valsprops = valsprops[0:2]
vetsprops = vetsprops[:, 0:2]
valsprops, vetsprops

(array([176.27502282, 107.76237238]),
 matrix([[ 0.69655167,  0.12282659],
         [ 0.13494668, -0.99008273],
         [ 0.70470219,  0.06818953]]))

In [39]:
phi = np.array([0.09710545, 2.18567601, 0.0364491])
phi = phi.reshape(1,3)


L = []
for i in range(2):
    L.append([phi.dot(vetsprops[:, i]).item()])
    

C = np.array(L)
proj = vetsprops.dot(C)
proj

    
    

matrix([[0.00642671],
        [2.18066581],
        [0.12703848]])

A USAR SVD

In [40]:
e_faces, sigma, v = np.linalg.svd(S.transpose(), full_matrices=False)
val_prop = sigma*sigma
traco = sum(val_prop)


val_prop, v.transpose()










(array([31072.88367126, 11612.72890057,   402.77130086]),
 matrix([[-0.69655167,  0.12282659, -0.70691542],
         [-0.13494668, -0.99008273, -0.03905863],
         [-0.70470219,  0.06818953,  0.70621882]]))

In [41]:
confianca = 0
cumsum = 0
i = 0
while confianca < 0.9:
    cumsum = cumsum + val_prop[i]
    confianca = cumsum / traco
    i+=1



principal_components= (v.transpose())[:, 0:i]
val_prop = val_prop[0:i]
val_prop, principal_components



(array([31072.88367126, 11612.72890057]),
 matrix([[-0.69655167,  0.12282659],
         [-0.13494668, -0.99008273],
         [-0.70470219,  0.06818953]]))

In [42]:
phi = np.array([0.09710545, 2.18567601, 0.0364491])
phi = phi.reshape(1,3)

arr = []
for j in range(i):
    Ci = (np.dot(phi, principal_components[:, j])).item()
    arr.append([Ci])
C = np.array(arr)

proj = np.dot(principal_components, C)
proj

matrix([[0.00642671],
        [2.18066581],
        [0.12703848]])