In [19]:
import numpy as np

A = np.array([[9,26,5], [3,1,-19], [28,100,31]])
   

def gram_schmidt(A):
    m, n = A.shape
    Q = np.zeros((m, n))
    Q[:, 0] = A[:, 0] / np.linalg.norm(A[:, 0], 2)
    for i in range(1, n):
        Q[:, i] = A[:, i]
        for j in range(0, i):
            inner = np.dot(Q[:, j].T, Q[:, i])
            Q[:, i] = Q[:, i] - np.dot(inner, Q[:, j])
        Q[:, i] = Q[:, i] / np.linalg.norm(Q[:, i], 2)
    return Q



def qr_gs(A):
    m, n = A.shape
    Q = gram_schmidt(A)
    R = np.zeros((m, n))
    for i in range(0, n):
        R[i, i] = np.dot(Q[:, i], A[:, i])
        for j in range(0, i):
            R[j, i] = np.dot(Q[:, j], A[:, i])
    return Q, R
        

Q,R = qr_gs(A)
print(Q)
print(f"\n{R}")
print(f"\n{np.dot(Q,R)}")
print(f"\n{np.dot(Q,Q.transpose())}")


[[ 0.30442954 -0.47367299  0.82641185]
 [ 0.10147651 -0.84652733 -0.52258397]
 [ 0.94711413  0.24295139 -0.20964124]]

[[ 29.563491   102.72805739  28.95463192]
 [  0.          11.13311386  21.24714736]
 [  0.           0.           7.5622761 ]]

[[  9.  26.   5.]
 [  3.   1. -19.]
 [ 28. 100.  31.]]

[[ 1.00000000e+00  4.56497051e-16  4.62655648e-15]
 [ 4.56497051e-16  1.00000000e+00 -1.24476974e-15]
 [ 4.62655648e-15 -1.24476974e-15  1.00000000e+00]]
